#!/bin/bash

# Clear the screen
clear

# Check if Python is installed, if not, install it
if ! command -v python &> /dev/null; then
    echo -e "\033[93mPython is not installed. Installing Python...\033[0m"
    apt update && apt install -y python
fi

clear

# Update and Upgrade
echo -e "\033[93mUpdating and Upgrading...\033[0m"
pkg update -y && pkg upgrade -y

# Clear the screen
clear

# Display banner
echo -e "\033[91m
 _____   ____   ____  __  __  _____          __  __ ______ ___  ___  __  
|  __ \ / __ \ / __ \|  \/  |/ ____|   /\   |  \/  |  ____|__ \|__ \/_ |
| |  | | |  | | |  | | \  / | |  __   /  \  | \  / | |__     ) |  ) || |
| |  | | |  | | |  | | |\/| | | |_ | / /\ \ | |\/| |  __|   / /  / / | |
| |__| | |__| | |__| | |  | | |__| |/ ____ \| |  | | |____ / /_ / /_ | |
|_____/ \____/ \____/|_|  |_|\_____/_/    \_\_|  |_|______|____|____||_|
"

# Custom "CREATED BY" with different colors for "DG" and "221"
echo -e "CREATED BY\033[94m DG\033[92m 221"

echo -e "\033[93m
+---------------------------------------+ 
| This Tool Installs All Basic Packages |
+---------------------------------------+ 
|    Coded By DG221 | Version: 2.9      |
+---------------------------------------+ 
"

# List of packages
packages=(
    python python2 proot-distro git perl
    bash nano curl openssl openssh wget clang nmap
    w3m hydra ruby macchanger host dnsutils coreutils
    fish zip figlet cowsay unzip vim golang rust
    sqlite nodejs-lts tcpdump ettercap net-tools iproute2
    termux-api ffmpeg imagemagick sox htop tree neofetch
    screen tmux mpv metasploit sqlmap nikto ubuntu
)

# Sort the packages alphabetically
sorted_packages=($(printf '%s\n' "${packages[@]}" | sort))

# Function to check if a package is installed
is_installed() {
    dpkg -l | grep -qw "$1"
}

# Display the list of packages with color coding for installed packages
echo -e "\033[93m
Available packages (A-Z):
"

# Display numbered list of packages with color based on installation status
for i in "${!sorted_packages[@]}"; do
    pkg="${sorted_packages[i]}"
    if is_installed "$pkg"; then
        # If package is installed, show in green
        echo -e "\033[92m[$((i + 1))] $pkg (Installed)\033[0m"
    else
        # If package is not installed, show in yellow
        echo -e "\033[93m[$((i + 1))] $pkg\033[0m"
    fi
done
echo -e "[99] Install All"
echo -e "[00] Exit"

# Prompt user to choose packages to install
while true; do
    echo -e "\033[96mChoose a package to install or update by entering the number (or 99 to install all, 00 to exit):"
    read -p "Enter your choice: " choice

    if [[ "$choice" == "00" ]]; then
        echo -e "\033[91mExiting installation...\033[0m"
        break
    elif [[ "$choice" == "99" ]]; then
        echo -e "\033[92mInstalling/updating all packages...\033[0m"
        for pkg in "${sorted_packages[@]}"; do
            echo -e "\033[93mInstalling/updating $pkg...\033[0m"
            if [[ "$pkg" == "hydra" ]]; then
                echo -e "\033[93mInstalling dependencies for hydra...\033[0m"
                apt install -y build-essential libssl-dev libssh-dev
            fi
            if is_installed "$pkg"; then
                echo -e "\033[93m$pkg is already installed, updating...\033[0m"
                apt install --only-upgrade -y "$pkg"
            else
                if apt install -y "$pkg"; then
                    echo -e "\033[92m$pkg installed successfully!\033[0m"
                else
                    echo -e "\033[91mFailed to install $pkg.\033[0m"
                fi
            fi
        done
        echo -e "\033[92mAll packages installed or updated!\033[0m"
        break
    elif [[ "$choice" -ge 1 && "$choice" -le ${#sorted_packages[@]} ]]; then
        selected_pkg="${sorted_packages[$((choice - 1))]}"
        echo -e "\033[92mInstalling/updating $selected_pkg...\033[0m"

        if [[ "$selected_pkg" == "ubuntu" ]]; then
            echo -e "\033[93m$selected_pkg is already installed, updating...\033[0m"
            pkg install proot-distro
            pd install ubuntu
            pd login ubuntu
        fi

        if is_installed "$selected_pkg"; then
            echo -e "\033[93m$selected_pkg is already installed, updating...\033[0m"
            apt install --only-upgrade -y "$selected_pkg"
        else
            if apt install -y "$selected_pkg"; then
                echo -e "\033[92m$selected_pkg installed successfully!\033[0m"
            else
                echo -e "\033[91mFailed to install $selected_pkg.\033[0m"
            fi
        fi
    fi
done

# Final message
echo -e "\033[95m
+---------------------------------------+
|       Thank you for using DG221       |
|   Ready to explore and create more!   |
+---------------------------------------+
"
read -p "Press Enter to exit."

clear
